const products = [
  {
    id: "1",
    name: "Nike Air Max 270 React",
    price: parseFloat("600.43"),
    oldPrice: parseFloat("750.33"),
    image: "/imges/image Product4.png",
    discount: "24% off",
  },
  {
    id: "2",
    name: "Nike Air Max 290 React",
    price: parseFloat("600.43"),
    oldPrice: parseFloat("750.33"),
    image: "/imges/image Product (2).png",
    discount: "24% off",
  },
  {
    id: "3",
    name: "Nike Air Max 270 React",
    price: parseFloat("670.43"),
    oldPrice: parseFloat("750.33"),
    image: "/imges/image Product3.png",
    discount: "24% off",
  },
  {
    id: "4",
    name: "Nike Air Max 270 React",
    price: parseFloat("620.43"),
    oldPrice: parseFloat("750.33"),
    image: "/imges/image Product1.png",
    discount: "24% off",
  },
  {
    id: "5",
    name: "Nike Air Max 270 React",
    price: parseFloat("900.43"),
    oldPrice: parseFloat("750.33"),
    image: "/imges/Product Picture5.png",
    discount: "24% off",
  },
  {
    id: "6",
    name: "Nike Air Max 270 React",
    price: parseFloat("700.43"),
    oldPrice: parseFloat("750.33"),
    image: "/imges/Product Picture7.png",
    discount: "24% off",
  },
  {
    id: "7",
    name: "Nike Air Max 270 React",
    price: parseFloat("600.43"),
    oldPrice: parseFloat("750.33"),
    image: "/imges/image Product (2).png",
    discount: "24% off",
  },
  {
    id: "8",
    name: "Nike Air Max 270 React",
    price: parseFloat("650.43"),
    oldPrice: parseFloat("750.33"),
    image: "/imges/Promotion Image.png",
    discount: "24% off",
  },
  {
    id: "9",
    name: "Nike Air Max 270 React",
    price: parseFloat("607.43"),
    oldPrice: parseFloat("750.33"),
    image: "/imges/image Product (1).png",
    discount: "24% off",
  },
  {
    id: "10",
    name: "Nike Air Max 270 React",
    price: parseFloat("500.43"),
    oldPrice: parseFloat("750.33"),
    image: "/imges/Product Picture5.png",
    discount: "24% off",
  },
  {
    id: "11",
    name: "Nike Air Max 270 React",
    price: parseFloat("680.43"),
    oldPrice: parseFloat("750.33"),
    image: "/imges/image Product3.png",
    discount: "24% off",
  },
  {
    id: "12",
    name: "Nike Air Max 270 React",
    price: parseFloat("600.43"),
    oldPrice: parseFloat("750.33"),
    image: "/imges/Product Picture5.png",
    discount: "24% off",
  },
  {
    id: "13",
    name: "Nike Air Max 270 React",
    price: parseFloat("606.43"),
    oldPrice: parseFloat("750.33"),
    image: "/imges/image Product3.png",
    discount: "24% off",
  },
  {
    id: "14",
    name: "Nike Air Max 270 React",
    price: parseFloat("600.43"),
    oldPrice: parseFloat("750.33"),
    image: "/imges/Product Picture5.png",
    discount: "24% off",
  },
  {
    id: "15",
    name: "Nike Air Max 270 React",
    price: parseFloat("600.43"),
    oldPrice: parseFloat("750.33"),
    image: "/imges/image Product4.png",
    discount: "24% off",
  },
  {
    id: "16",
    name: "Nike Air Max 270 React",
    price: parseFloat("600.43"),
    oldPrice: parseFloat("750.33"),
    image: "/imges/image Product (2).png",
    discount: "24% off",
  },
];

export default products;
